[project]
name = "awss3testagain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aioboto3>=14.1.0",
    "mcp[cli]>=1.5.0",
]
